language: scala
scala: 2.10.2
before_install:
- sudo apt-get update
- sudo apt-get install cabal-install
install:
- cabal install
before_script: touch /tmp/testres1.txt /tmp/testres2.txt
script: ./compare-algos.sh 10

